declare module "three" {
  export type BoxGeometry = any;
  export type CanvasTexture = any;
  export type Color = any;
  export type DirectionalLight = any;
  export type Fog = any;
  export type GridHelper = any;
  export type Group = any;
  export type HemisphereLight = any;
  export type Mesh = any;
  export type MeshBasicMaterial = any;
  export type MeshStandardMaterial = any;
  export type Object3D = any;
  export type PerspectiveCamera = any;
  export type PlaneGeometry = any;
  export type Scene = any;
  export type SpotLight = any;
  export type Sprite = any;
  export type SpriteMaterial = any;
  export type Texture = any;
  export type TextureLoader = any;
  export type Vector3 = any;
  export type WebGLRenderer = any;

  export const BoxGeometry: any;
  export const CanvasTexture: any;
  export const Color: any;
  export const DirectionalLight: any;
  export const Fog: any;
  export const GridHelper: any;
  export const Group: any;
  export const HemisphereLight: any;
  export const MathUtils: any;
  export const Mesh: any;
  export const MeshBasicMaterial: any;
  export const MeshStandardMaterial: any;
  export const NearestFilter: any;
  export const Object3D: any;
  export const PCFShadowMap: any;
  export const PerspectiveCamera: any;
  export const PlaneGeometry: any;
  export const Scene: any;
  export const SpotLight: any;
  export const Sprite: any;
  export const SpriteMaterial: any;
  export const SRGBColorSpace: any;
  export const Texture: any;
  export const TextureLoader: any;
  export const Vector3: any;
  export const WebGLRenderer: any;
}
